In [1]:
from pandas_datareader import data
from datetime import datetime as dt
from bokeh.plotting import figure, show, output_file
from bokeh.embed import components
from bokeh.resources import CDN

In [2]:
start = dt(2015, 11, 1)
end = dt(2016, 3, 1)

df = data.DataReader(name='GOOG', data_source='yahoo', start=start, end=end)

In [3]:
def inc_dec(close, open):
    if close > open:
        value = 'Increase'
    elif close < open:
        value = 'Decrease'
    else:
        value = 'Equal'
    return value

df['Status'] = [inc_dec(c, o) for c, o in zip(df.Close, df.Open)]
df['Average'] = (df.Open + df.Close)/2
df['Height'] = abs(df.Open - df.Close)

In [4]:
df

,High,Low,Open,Close,Volume,Adj Close,Status,Average,Height
Date,,,,,,,,,
2015-11-02,721.619995,705.849976,711.059998,721.109985,1886300,721.109985,Increase,716.084991,10.049988
2015-11-03,724.650024,714.719971,718.859985,722.159973,1565400,722.159973,Increase,720.509979,3.299988
2015-11-04,733.099976,721.900024,722.000000,728.109985,1706700,728.109985,Increase,725.054993,6.109985
2015-11-05,739.479980,729.469971,729.469971,731.250000,1861600,731.250000,Increase,730.359985,1.780029
2015-11-06,735.409973,727.010010,731.500000,733.760010,1511600,733.760010,Increase,732.630005,2.260010
...,...,...,...,...,...,...,...,...,...
2016-02-24,700.000000,680.780029,688.919983,699.559998,1963600,699.559998,Increase,694.239990,10.640015
2016-02-25,705.979980,690.585022,700.010010,705.750000,1642200,705.750000,Increase,702.880005,5.739990
2016-02-26,713.429993,700.859985,708.580017,705.070007,2243500,705.070007,Decrease,706.825012,3.510010
2016-02-29,710.890015,697.679993,700.320007,697.770020,2481100,697.770020,Decrease,699.045013,2.549988
2016-03-01,718.809998,699.770020,703.619995,718.809998,2151400,718.809998,Increase,711.214996,15.190002

In [5]:
def rect_build(plot, status, color):
    hours_in_ms = 12*60*60*1000
    plot.rect(df.index[df.Status == status], df.Average[df.Status == status], hours_in_ms, 
          df.Height[df.Status == status], fill_color=color, line_color='black', legend_label=status)

In [6]:
plot = figure(x_axis_type='datetime', width=1000, height=300, sizing_mode='scale_width')
plot.title.text = 'Candlestick Chart'
plot.grid.grid_line_alpha = 0.3
plot.segment(df.index, df.High, df.index, df.Low, color='Black')

rect_build(plot, 'Increase', '#7B9B74')
rect_build(plot, 'Decrease', '#FF6C00')
rect_build(plot, 'Equal', '#C4C7CC')

# output_file('CS.html')
# show(plot)

In [9]:
script1, div1 = components(plot)
cdn_js = CDN.js_files
cdn_css = CDN.css_files